#!/bin/sh
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
PATH="$PATH:/usr/local/sdkman/candidates/kotlin/current/bin"
#kotlin -cp /var/lib/judgehost/judgings/icpc-tw/endpoint-default/executable/verifyD/ VerifyDKt "$1" "$2"
kotlin -cp ${SCRIPTPATH} VerifyAKt "$1" "$2"
exit $?
